Add Dockerfile

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -9,28 +9,33 @@ jobs:
   export-linux:
     name: Linux Export
     runs-on: ubuntu-latest
-    container:
-      image: barichello/godot-ci:4.2.1
+
     steps:
       - name: Checkout
         uses: actions/checkout@v4
         with:
           lfs: true
-      - name: Setup
+
+      - name: Build Docker image
+        run: docker build . -t godot:latest .
+
+      - name: Setup and Linux Build
         run: |
-          mkdir -v -p ~/.local/share/godot/export_templates/
-          ls /root/.local/share/godot/export_templates/
-          mv /root/.local/share/godot/export_templates/${GODOT_VERSION} ~/.local/share/godot/export_templates/${GODOT_VERSION}
-      - name: Linux Build
-        run: |
-          mkdir -v -p build/linux
-          cd ./godot
-          output=$(godot --headless --verbose --export-release "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64)
-          echo "$output" | grep "with error"
-          if [ $? -eq 0 ]; then
-            echo "Error detected"
-            exit 1
-          fi
+          docker run --name godot-container -v "${{ github.workspace }}:/workspace" godot:latest /bin/bash -c "
+          mkdir -vp ~/.local/share/godot/export_templates/ &&
+            ls /root/.local/share/godot/export_templates/ &&
+            mv /root/.local/share/godot/export_templates/${{ GODOT_VERSION }} ~/.local/share/godot/export_templates/${{ GODOT_VERSION }} &&
+            mkdir -vp /workspace/build/linux &&
+            cd /workspace/godot &&
+            output=\$(godot --headless --verbose --export-release \"Linux/X11\" /workspace/build/linux/$EXPORT_NAME.x86_64) &&
+            echo \"\$output\" &&
+            echo \"\$output\" | grep 'with error' &&
+            if [ \$? -eq 0 ]; then
+              echo 'Error detected' &&
+              exit 1;
+            fi
+          "
+
       - name: Upload Artifact
         uses: actions/upload-artifact@v4
         with:
