Grep with error

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -24,7 +24,12 @@ jobs:
         run: |
           mkdir -v -p build/linux
           cd ./godot
-          godot --headless --verbose --export-release "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
+          output=$(godot --headless --verbose --export-release "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64)
+          echo "$output" | grep "with error"
+          if [ $? -eq 0 ]; then
+            echo "Error detected"
+            exit 1
+          fi
       - name: Upload Artifact
         uses: actions/upload-artifact@v4
         with:
